kind: pipeline
type: docker #在docker環境中執行
name: test #自定義pipleline名稱

steps: #工作列表

  - name: ssh-deploy
    when:
      event: tag
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: sshhost
      username:
        from_secret: sshname
      key:
        from_secret: sshkey
      port: 22
      command_timeout: 2m
      script:
        - echo hello